-- Importando Dados de 2023
COPY dados_2023 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2023/1T2023.csv'
WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', DELIMITER ';');

COPY dados_2023 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2023/2T2023.csv'
WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', DELIMITER ';');

COPY dados_2023 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2023/3T2023.csv'
WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', DELIMITER ';');

COPY dados_2023 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2023/4T2023.csv'
WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', DELIMITER ';');

UPDATE dados_2023 SET VL_SALDO_INICIAL = REPLACE(VL_SALDO_INICIAL, ',', '.')::NUMERIC;
UPDATE dados_2023 SET VL_SALDO_FINAL = REPLACE(VL_SALDO_FINAL, ',', '.')::NUMERIC;

SELECT * FROM DADOS_2023;
