-- Importando Dados de 2024
COPY dados_2024 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2024/1T2024.csv'
WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', DELIMITER ';');

COPY dados_2024 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2024/2T2024.csv'
WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', DELIMITER ';');

COPY dados_2024 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2024/3T2024.csv'
WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', DELIMITER ';');

COPY dados_2024 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2024/4T2024.csv'
WITH (FORMAT CSV, HEADER, ENCODING 'UTF8', DELIMITER ';');

UPDATE dados_2024 SET VL_SALDO_INICIAL = REPLACE(VL_SALDO_INICIAL, ',', '.')::NUMERIC;
UPDATE dados_2024 SET VL_SALDO_FINAL = REPLACE(VL_SALDO_FINAL, ',', '.')::NUMERIC;

SELECT * FROM DADOS_2024;

