-- Importando Dados de 2023
COPY dados_2023 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2023/1T2023.csv'
DELIMITER ';'
CSV HEADER;

COPY dados_2023 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2023/2T2023.csv'
DELIMITER ';'
CSV HEADER;

COPY dados_2023 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2023/3T2023.csv'
DELIMITER ';'
CSV HEADER;

COPY dados_2023 (DATAS,REG_ANS,CD_CONTA_CONTABIL,DESCRICAO,VL_SALDO_INICIAL,VL_SALDO_FINAL)
FROM 'C:/Project-Python/Python_Postgres/dados_2023/4T2023.csv'
DELIMITER ';'
CSV HEADER;


SELECT * FROM DADOS_2023;
